monitor = desc: Chimei Innolux Corporation 0x152E, 1920x1080@60.00, 0x0, 1
monitor = , preferred, auto, 1, mirror, desc: Chimei Innolux Corporation 0x152E
monitor = desc: Acer Technologies B226WL LXVEE0018510, 1680x1050@75.00, -1680x0, 1
